package io.fdeitylink.keroedit.image

const val TILE_WIDTH = 8
const val TILE_HEIGHT = 8

const val TILES_PER_ROW = 16
const val TILES_PER_COLUMN = 16

const val TILESET_WIDTH = TILE_WIDTH * TILES_PER_ROW
const val TILESET_HEIGHT = TILE_HEIGHT * TILES_PER_COLUMN

const val PXATTR_TILE_WIDTH = 16
const val PXATTR_TILE_HEIGHT = 16

const val PXATTR_TILES_PER_ROW = 16
const val PXATTR_TILES_PER_COLUMN = 8

const val PXATTR_IMAGE_WIDTH = PXATTR_TILE_WIDTH * PXATTR_TILES_PER_ROW
const val PXATTR_IMAGE_HEIGHT = PXATTR_TILE_HEIGHT * PXATTR_TILES_PER_COLUMN

const val PXATTR_TO_TILE_RATIO = PXATTR_TILE_WIDTH / TILE_WIDTH

const val ENTITY_WIDTH = 16

const val ENTITY_HEIGHT = 16
const val ENTITIES_PER_ROW = 16

const val ENTITIES_PER_COLUMN = 11
const val ENTITY_IMAGE_WIDTH = ENTITY_WIDTH * ENTITIES_PER_ROW

const val ENTITY_IMAGE_HEIGHT = ENTITY_HEIGHT * ENTITIES_PER_COLUMN

const val ENTITY_TO_TILE_RATIO = ENTITY_IMAGE_WIDTH / TILESET_WIDTH